config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
  resources :categories
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts

  validates :name, presence: true, length: { maximum: 20 }
  validates :title, length: { maximum: 100 }
  validates :description, length: { maximum: 500 }
  validates :sidebar, length: { maximum: 5120 }
  validates :submission_text, length: { maximum: 1024 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category

  validates :category_id, presence: true
  validates :title, length: { maximum: 500 }, presence: true
  validates :link, presence: true, if: :link?
  validates :body, presence: true, if: :text?

  enum post_type: [:link, :text]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show]

  def show

  end


  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      redirect_to posts_path, flash: { notice: 'Thanks for creating a category.' }
    else
      flash.now[:error] = @category.errors.full_messages
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :title, :description, :sidebar, :submission_text)
  end

  def find_category
    @category = Category.find params[:id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to post_path(@post), flash: { notice: 'Thank you for updating your post.' }
    else
      flash.now[:error] = @post.errors.full_messages
      render :edit
    end
  end

  def new
    @post = Post.new
    @post.post_type = params[:post_type] if params[:post_type].present?
  end

  def create
    @post = Post.new post_params
    if @post.save
      redirect_to posts_path, flash: { notice: 'Thank you for submitting your post.' }
    else
      flash.now[:error] = @post.errors.full_messages
      render :new
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path, flash: { notice: 'Your post has been removed.' }
    else
      redirect_to post_path(@post), flash: { error: 'We were unable to remove that post.' }
    end
  end

  private

  def find_post
    @post = Post.find params[:id]
  end

  def post_params
    params.require(:post).permit(
      :title,
      :link,
      :body,
      :post_type,
      :category_id
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(name)
    bootstrap_class = case name.to_s
      when 'notice'  then 'alert-success'
      when 'error'   then 'alert-danger'
      when 'alert'   then 'alert-danger'
      when 'info'    then 'alert-info'
      when 'warning' then 'alert-warning'
      else "alert-#{name}"
    end
    bootstrap_class
  end

  def post_link(post)
    return post.link if post.link?
    return post_path(post) if post.text?
  end

  def sidebar(sidebar_content)
      content_for(:sidebar) {sidebar_content}
  end

end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <fieldset>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </fieldset>

  <fieldset>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </fieldset>

  <fieldset>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </fieldset>

  <fieldset>
    <%= f.label :sidebar %>
    <%= f.text_area :sidebar %>
  </fieldset>

  <fieldset>
    <%= f.label :submission_text %>
    <%= f.text_area :submission_text %>
  </fieldset>

  <%= f.submit class: 'btn btn-default' %>
<% end %>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<div class="category">
  <h2><%= @category.title %></h2>
  <div class="description"><%= @category.description %></div>
</div>

<%sidebar @category.sidebar %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container wrap">
  <div class="row">
    <div class="col-xs-12">
      <header>
        <%= link_to 'Redly', root_path %>
      </header>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-8">
        <main>
          <% flash.each do |name, msg| %>
            <% if msg.is_a? Array %>
              <div class="alert <%= flash_class name %>">
                <ul>
                  <% msg.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% else %>
              <%= content_tag :div, msg, class: "alert #{flash_class name}" %>
            <% end %>
          <% end %>
          <!-- BEGIN main content -->
          <%= yield %>
          <!-- END main content -->
        </main>
      </div>
      <div class="col-xs-4">
        <nav id="sidebar">
          <%= link_to 'Submit a new link', new_post_path %>
          <%= link_to 'Submit a new text post', new_post_path(post_type: :text) %>
          <%= link_to 'Create a new category', new_category_path %>
          <div><%= yield :sidebar %></div>
      </nav>
      </div>
    </div>
  </div>
  <div class="push"></div>
</div>

<footer>
  &copy; 2015.
    Use of this site constitutes acceptance of the <a href="http://dresdenfiles.wikia.com/wiki/Unseelie_Accords">Unseelie Accords</a>.
</footer>

</body>
</html>

app/views/posts/_actions.html.erb
<ul class="actions">
  <li><%= link_to 'edit', edit_post_path(post) %></li>
  <li><%= link_to 'delete', post_path(post), method: :delete, data: { confirm: 'Are you sure? This cannot be undone.' } %></li>
</ul>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <fieldset>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </fieldset>

  <fieldset>
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id,:name, prompt: 'Select a category' %>  
  </fieldset>


  <% if f.object.link? %>
    <fieldset>
      <%= f.label :link %>
      <%= f.url_field :link %>
    </fieldset>
  <% end %>

  <% if f.object.text? %>
    <fieldset>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </fieldset>
  <% end %>

  <%= f.hidden_field :post_type %>
  <%= f.submit class: 'btn btn-default' %>
<% end %>

app/views/posts/_slug.html.erb
<div class="title"><%= link_to post.title, post_link(post) %></div>
<div class="tagline" title="<%= post.created_at %>">
  <%= time_ago_in_words post.created_at %> ago
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<ul class="posts">
<% @posts.each do |post| %>
  <li>
    <%= render 'slug', post: post %>
    <%= render 'actions', post: post %>
  </li>
<% end %>
</ul>

app/views/posts/show.html.erb
<article class="post">
  <%= render 'slug', post: @post %>

  <% if @post.text? -%>
    <section class="body"><%= @post.body %></section>
  <% end -%>

  <%= render 'actions', post: @post %>
</article>